/*
 * Merchant API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vimando.api.merchant.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OrderImportList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-08T08:43:24.704+02:00")
public class OrderImportList implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("orderImports")
  private List<OrderImport> orderImports = null;

  public OrderImportList count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public OrderImportList orderImports(List<OrderImport> orderImports) {
    this.orderImports = orderImports;
    return this;
  }

  public OrderImportList addOrderImportsItem(OrderImport orderImportsItem) {
    if (this.orderImports == null) {
      this.orderImports = new ArrayList<OrderImport>();
    }
    this.orderImports.add(orderImportsItem);
    return this;
  }

   /**
   * Get orderImports
   * @return orderImports
  **/
  @ApiModelProperty(value = "")
  public List<OrderImport> getOrderImports() {
    return orderImports;
  }

  public void setOrderImports(List<OrderImport> orderImports) {
    this.orderImports = orderImports;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderImportList orderImportList = (OrderImportList) o;
    return Objects.equals(this.count, orderImportList.count) &&
        Objects.equals(this.orderImports, orderImportList.orderImports);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, orderImports);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderImportList {\n");

    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    orderImports: ").append(toIndentedString(orderImports)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

