/*
 * Merchant API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vimando.api.merchant.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OrderDelivery
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-08T08:43:24.704+02:00")
public class OrderDelivery implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("history")
  private List<OrderStateHistory> history = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("number")
  private String number = null;

  @JsonProperty("products")
  private List<String> products = null;

  @JsonProperty("state")
  private String state = null;

  @JsonProperty("stateCode")
  private String stateCode = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("trackingCode")
  private String trackingCode = null;

  @JsonProperty("trackingUrl")
  private String trackingUrl = null;

  public OrderDelivery history(List<OrderStateHistory> history) {
    this.history = history;
    return this;
  }

  public OrderDelivery addHistoryItem(OrderStateHistory historyItem) {
    if (this.history == null) {
      this.history = new ArrayList<OrderStateHistory>();
    }
    this.history.add(historyItem);
    return this;
  }

   /**
   * Get history
   * @return history
  **/
  @ApiModelProperty(value = "")
  public List<OrderStateHistory> getHistory() {
    return history;
  }

  public void setHistory(List<OrderStateHistory> history) {
    this.history = history;
  }

  public OrderDelivery id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OrderDelivery number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @ApiModelProperty(value = "")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public OrderDelivery products(List<String> products) {
    this.products = products;
    return this;
  }

  public OrderDelivery addProductsItem(String productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<String>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * Get products
   * @return products
  **/
  @ApiModelProperty(value = "")
  public List<String> getProducts() {
    return products;
  }

  public void setProducts(List<String> products) {
    this.products = products;
  }

  public OrderDelivery state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public OrderDelivery stateCode(String stateCode) {
    this.stateCode = stateCode;
    return this;
  }

   /**
   * Get stateCode
   * @return stateCode
  **/
  @ApiModelProperty(value = "")
  public String getStateCode() {
    return stateCode;
  }

  public void setStateCode(String stateCode) {
    this.stateCode = stateCode;
  }

  public OrderDelivery text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @ApiModelProperty(value = "")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public OrderDelivery trackingCode(String trackingCode) {
    this.trackingCode = trackingCode;
    return this;
  }

   /**
   * Get trackingCode
   * @return trackingCode
  **/
  @ApiModelProperty(value = "")
  public String getTrackingCode() {
    return trackingCode;
  }

  public void setTrackingCode(String trackingCode) {
    this.trackingCode = trackingCode;
  }

  public OrderDelivery trackingUrl(String trackingUrl) {
    this.trackingUrl = trackingUrl;
    return this;
  }

   /**
   * Get trackingUrl
   * @return trackingUrl
  **/
  @ApiModelProperty(value = "")
  public String getTrackingUrl() {
    return trackingUrl;
  }

  public void setTrackingUrl(String trackingUrl) {
    this.trackingUrl = trackingUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderDelivery orderDelivery = (OrderDelivery) o;
    return Objects.equals(this.history, orderDelivery.history) &&
        Objects.equals(this.id, orderDelivery.id) &&
        Objects.equals(this.number, orderDelivery.number) &&
        Objects.equals(this.products, orderDelivery.products) &&
        Objects.equals(this.state, orderDelivery.state) &&
        Objects.equals(this.stateCode, orderDelivery.stateCode) &&
        Objects.equals(this.text, orderDelivery.text) &&
        Objects.equals(this.trackingCode, orderDelivery.trackingCode) &&
        Objects.equals(this.trackingUrl, orderDelivery.trackingUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(history, id, number, products, state, stateCode, text, trackingCode, trackingUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderDelivery {\n");

    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    stateCode: ").append(toIndentedString(stateCode)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    trackingCode: ").append(toIndentedString(trackingCode)).append("\n");
    sb.append("    trackingUrl: ").append(toIndentedString(trackingUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

